export const data = {
    name: 'Bakery Snacks',
    value: 1,
    n: 301,
    rank: 74,
    children: [
        {
            name: 'Planned',
            color: '#d8d8d8',
            children: [
                {
                    name: 'No promotion',
                    color: '#d8d8d8',
                    value: 0.66,
                    category: 0.69,
                    benchmark: 0.68,
                    rank: 48,
                    children: [
                        {
                            name: 'Regular purchase',
                            value: 0.52,
                            category: 0.59,
                            benchmark: 0.56,
                            rank: 45,
                        },
                        {
                            name: 'Particular use',
                            value: 0.15,
                            category: 0.10,
                            benchmark: 0.12,
                            rank: 62,
                        },
                        {
                            name: 'Requested',
                            value: 0.08,
                            category: 0.17,
                            benchmark: 0.08,
                            rank: 4,
                            color: '#01b050',
                        },
                        {
                            name: 'Try for a change',
                            value: 0.02,
                            category: 0.05,
                            benchmark: 0.02,
                            rank: 18,
                            color: '#90cd4f',
                        },
                    ],
                },
                {
                    name: 'Promotion trigger',
                    value: 0.8,
                    color: '#01b050',
                    category: 0.14,
                    benchmark: 0.07,
                    rank: 9,
                    children: [
                        {
                            name: 'Catalogue',
                            value: 0.06,
                            category: 0.07,
                            benchmark: 0.05,
                            rank: 25,
                        },
                        {
                            name: 'Advert',
                            value: 0.01,
                            category: 0.05,
                            benchmark: 0.01,
                            rank: 6,
                            color: '#01b050',
                        },
                        {
                            name: 'Internet info',
                            value: 0.01,
                            category: 0.03,
                            benchmark: 0.01,
                            rank: 7,
                            color: '#01b050',
                        },
                        {
                            name: 'Coupon',
                            value: 0.01,
                            category: 0.06,
                            benchmark: 0.01,
                            rank: 1,
                            color: '#01b050',
                        },
                    ],
                },
            ],
            value: 0.71,
            category: 0.74,
            benchmark: 0.72,
            rank: 47,
        },
        {
            name: 'Unplanned',
            children: [
                {
                    name: 'No promotion',
                    value: 0.16,
                    category: 0.17,
                    benchmark: 0.16,
                    rank: 57,
                },
                {
                    name: 'Promotion trigger',
                    value: 0.15,
                    category: 0.15,
                    benchmark: 0.15,
                    rank: 64,
                    children: [
                        {
                            name: 'Price specials',
                            value: 0.07,
                            category: 0.07,
                            benchmark: 0.08,
                            rank: 59,
                        },
                        {
                            name: 'Display',
                            value: 0.1,
                            category: 0.02,
                            benchmark: 0.01,
                            rank: 13,
                        },
                        {
                            name: 'Info in store',
                            color: '#90CD4F',
                            value: 0.02,
                            category: 0.03,
                            benchmark: 0.02,
                            rank: 31,
                        },
                        {
                            name: 'New',
                            value: 0.01,
                            category: 0,
                            benchmark: 0,
                            rank: 73,
                        },
                    ],
                },
            ],
            value: 0.25,
            category: 0.26,
            benchmark: 0.28,
            rank: 68,
        },
    ]
};